### ISSUE TITLE
Interest in replacing DevCon with PnPUtil for driver install?

### ISSUE THREAD

**Issue by forderud** [xxandy/USB_UDE_Sample#20]
I can help out on modernizing installation of the `hostude` and  `UDEFX2` drivers to use the in-built [PnPUtil](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/pnputil) instead of DevCon.

This will, if combined with certificate installation, have the benefit of getting rid of the following warning dialog when installing the drivers:
![image](https://github.com/xxandy/USB_UDE_Sample/assets/2671400/7c8f709e-dc49-4b0b-bc5c-9ff972f586cc)

Any interest in pull requests on this?

**Comment by xxandy** [comment]
wow that would be a great feature!

**Comment by forderud** [comment]
Great! I'll then start preparing a PR on DevCon to PnpUtil after #17 and #18 have been merged.
