### ISSUE TITLE
Uninstall / Disable Issue

### ISSUE THREAD

**Issue by MatthewTingum** [xxandy/USB_UDE_Sample#7]
Hello,

First off, thanks for this project!

I'm having trouble getting rid of this driver. I can use OSR Loader to unregister the service, reboot, then uninstall the driver. This gets to be a lot of waiting in the process of development / modification.

I apologize as I'm new to the world of driver development, but could this be an issue of unimplemented disconnect functions, or is it more likely that I'm doing something incorrectly?

**Comment by xxandy** [comment]
I haven't touched it in a while, but I could remove it just by right-clicking it in Device Manager UI, and asking to uninstall. No issues.

However: if you're doing it just for the sake of installing a newly-built version, your best bet is to use devcon.exe and "update" the driver - don't remove it.   Then you can get in a disable/update/enable cycle that spares you the trouble of removing the driver altogether.

cheers!
